name: empty_widget
description: Custom_Empty widget is flutter custom widget which is designed to notify user about some event.
version: 1.0.0
homepage: https://github.com/ElGenius-developer/flutter_empty_widget

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  custom_sizable_text: ^1.1.5+7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
   - assets/images/
  #

